//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POM
    {
        public string POID { get; set; }
        public string SUID { get; set; }
        public System.DateTime Date { get; set; }
        public string PMID { get; set; }
        public Nullable<System.DateTime> Paydate { get; set; }
        public decimal TAMT { get; set; }
        public System.DateTime bDate { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual POD POD { get; set; }
        public bool IsCompleted { get; internal set; }
    }
}
