//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WMSEntities2 : DbContext
    {
        public WMSEntities2()
            : base("name=WMSEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Import> Import { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<POD> POD { get; set; }
        public virtual DbSet<POM> POM { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Ship> Ship { get; set; }
        public virtual DbSet<SOD> SOD { get; set; }
        public virtual DbSet<SOM> SOM { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<StorageProduct> StorageProduct { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<AccountPassword> AccountPassword { get; set; }
    }
}
