//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOM
    {
        public string SOID { get; set; }
        public string CUID { get; set; }
        public System.DateTime Date { get; set; }
        public string PMID { get; set; }
        public System.DateTime EDL { get; set; }
        public string DLYaddress { get; set; }
        public System.DateTime bDate { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual SOD SOD { get; set; }
        public bool IsCompleted { get; internal set; }
    }
}
